config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "chatroom#index"
  get 'login', to: "sessions#new" 
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resource :message
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body , presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    validates :username , presence: true , length: {minimum: 3 , maximum: 20}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in? , :require_user
    # def current_user
    #     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # end
    def current_user
        if session[:user_id]
            @current_user = User.find(session[:user_id])
        end
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:error] = "You must logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    def index
        @message = Message.new
        @messages = Message.all
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    def create
        message = Message.new(message_params.merge(user_id: current_user.id))
        if message.save
            redirect_to root_path
        end
    end
    private
    def message_params
        params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
       @user = User.find_by(username: params[:session][:username])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            flash.now[:notice] = "you are sussfully login"
            redirect_to root_path
        else
            flash.now[:notice] = "please, provide correct username and password"
            render 'new' , status: 422
        end
    end
    def destroy
        session[:user_id] = nil
        flash.now[:notice] = "you have successfully logged out"
        redirect_to login_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<div class="container">
    <div class = "rounded  py-4">
        <!-- <img src = "../../assets/images/chit_chat.png "> -->
        <div class = "text-center">
            <%= image_tag 'chit_chat2.png', width: 160 ,height:160%>
        </div>
        <div class="row min-h py-4">
            <div class="col-md-8 ">
                <div class="shadow-lg p-3 mb-5 bg-color rounded h-100 d-flex justify-content-between flex-column">
                <table class = "text-left w-100">
                   <% @messages.each do |message| %>
                    <tr>
                      <td class = "px-3 " ><%= message.user.username %></td>
                      <td> <%= message.body %></td>
                    </tr>
                    <% end %>
                </table>



                <%= form_for(@message, url: message_path)  do |f| %>
                    <div class="form-group d-flex">
                        <%= f.text_field :body ,class: "form-control" %>
                        <%= f.button "send" , class: "btn btn-clr" %>
                    </div>
                <% end %>

                
                </div>
            </div>
            <div class="col-md-4">
                <div class="shadow-lg p-3 mb-5 bg-color rounded h-100">
                    <h4>Online friend's</h4>
                    <div class="nav nav_menus flex-column nav-pills text-left" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link" href = "#" text-white  >joe</a>
                        <a class="nav-link" href = "#" text-white >smith</a>
                        <a class="nav-link" href = "#" text-white  >dev</a>
                        <a class="nav-link" href = "#" text-white  >raiman</a>
                      </div>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand text-white" href="#">Chat App</a>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active text-white" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link text-white" href="#">Messages</a>
    </div>
    <div>
    <% if logged_in? %>
    <%= button_to "Logout", logout_path, method: :delete ,class: "btn btn-lg btn-clr text-white" %>
    <% else %>
     <%= link_to "Log in", login_path , class: "btn btn-lg btn-clr text-white" %>
    <% end %>
    <%# <button type="button" class="btn btn-lg btn-clr ">Log in</button> %>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>